### ISSUE TITLE
DataJoin REM visitor throws error w/nested data source

### ISSUE THREAD

**Issue by arvind** [vega/vega-encode#2]
In [this example](https://gist.github.com/arvind/95697aa6566c6f6580ee895f230766c5) (and apologies that I was not able to produce a more minimal one), I get the following error when trying to brush within a cell of the SPLOM referencing [line 60 of the DataJoin operator](https://github.com/vega/vega-encode/blob/master/src/DataJoin.js#L60).

```
vega.js:17293 Uncaught TypeError: Cannot read property 'datum' of null
```

As far as I can tell, the basic structure of a top-level dataset being filtered within a group mark using a nested signal should work (e.g., [this modified bar example](https://gist.github.com/arvind/57b98bc8bd163afa1a79487deca11ccb)) but I may have made some other mistake in my specification!

**Comment by jheer** [comment]
You are adding and removing the identical tuple on the same cycle:
`modify('brush_selection', brush_tuple, brush_tuple)` (L93)

If I change the update expression like so I stop seeing an error:
`modify('brush_selection', brush_tuple, true)`

But, I'm not 100% sure how you want this to work. Do you want to remove the previous brush_tuple (if it exists) and add the new one? If so, we may need to further update the modify method (an issue that should be filed against vega-parser).

**Comment by arvind** [comment]
Yes, I had wanted to do an "upsert" -- update the tuple if it exists in the dataset, and insert it otherwise. The `brush_selection` dataset may contain multiple distinct `brush_tuples` (e.g., if each cell of the SPLOM had its own brush) and so we cannot set `remove = true`. I recall us discussing this use case when we'd worked on `modify` and thought deleting and re-inserting the same tuple was the strategy we'd decided on but I might be misremembering. 

Will open a corresponding ticket in vega-parser!
