### ISSUE TITLE
Support time intervals for scale.nice

### ISSUE THREAD

**Issue by jheer** [vega/vega-encode#7]
Supersedes vega/vega#966.

**Comment by domoritz** [comment]
Related: https://github.com/vega/vega/issues/970

**Comment by jheer** [comment]
Fixed and released in vega-encode v2.0.1. Fixes handling of time interval specifiers for scale `nice` and axis/legend `tickCount`. Both interval strings (e.g., `"year"` or `"month"`) and interval objects (e.g., `{"interval": "year"}` or `{"interval": "month", "step": 3}` are supported.

Note that scale `nice` only modifies the scale domain, nothing else. To change the ticks that are generated, you must use an interval specification for the axis/legend `tickCount` property.
